-- User Info Table
CREATE TABLE userinfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
    CREATE TABLE secrets (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    mesaage BLOB NOT NULL,
    iv BLOB NOT NULL,
    salt  BLOL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES userinfo(id) ON DELETE CASCADE
);