-- User Info Table
CREATE TABLE userinfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE secrets (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    message MEDIUMTEXT NOT NULL,
    iv VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES userinfo(id) ON DELETE CASCADE
);

CREATE TABLE stats (
    id INT PRIMARY KEY DEFAULT 1,
    created_secrets INT NOT NULL DEFAULT 0,
    destroyed_secrets INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (id = 1)
);

INSERT INTO stats (id, created_secrets, destroyed_secrets)
VALUES (1, 0, 0);